vae:
  type: wfvae
  model_path: path_to_vae_ckpt
  latent_channels: 8
  dtype: bf16
  device: 'cuda:0'
  batch_size: 8

dataset:
  hf_shards: "hf://datasets/sailvideo/MiraData-v1/**/*.tar"
  num_workers: 4

  trg_fps: 8
  trg_res: 192
  trg_frames: 17

  counter_interval: 1000 # it/s print interval

  out_dtype: bf16
  out_folder: preprocess_dataset/out_enc
  out_batch_size: 16 # faster data loading